version: "3.9"

services:
  app:
    build: .
    container_name: botecovip
    restart: always
    ports:
      - 3001:3333
    volumes:
      - appbotecovip:/usr/app
      - /usr/app/node_modules

volumes:
  appbotecovip:
    driver: local